"""convert_to_uuid_and_add_redis

Revision ID: 312b1e8cffdf
Revises: 
Create Date: 2026-03-03 19:08:12.204775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = '312b1e8cffdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('skin_tone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('catalog_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('fit', sa.String(length=50), nullable=True),
    sa.Column('style_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('clip_embedding', pgvector.sqlalchemy.Vector(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_brand'), 'catalog_items', ['brand'], unique=False)
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_table('saved_outfits',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('playground', 'assistant')", name='ck_saved_outfits_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_outfits_user_id'), 'saved_outfits', ['user_id'], unique=False)
    op.create_table('wardrobe_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('fit', sa.String(length=50), nullable=True),
    sa.Column('style_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('clip_embedding', pgvector.sqlalchemy.Vector(dim=512), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_items_category'), 'wardrobe_items', ['category'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_category'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_index(op.f('ix_saved_outfits_user_id'), table_name='saved_outfits')
    op.drop_table('saved_outfits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_brand'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
